name: LavaDamage
version: '1.9'
main: com.ashkiano.lavadamage.LavaDamage
api-version: '1.16'
authors: [AshKiano]
description: This plugin inflicts heat damage on players who venture too close to lava, adding a new layer of danger to your Minecraft experience
website: https://www.ashkiano.com